version: '3.9'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  php:
    build: ./
    environment:
      PHP_IDE_CONFIG: "serverName=messenger"
    volumes:
      - ./:/app
#      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "messenger"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"

  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

  consumer:
    build: .
    depends_on:
      - rabbitmq3
      - php
    command: php bin/console messenger:consume async --time-limit=3600 --memory-limit=128M --no-interaction
    volumes:
      - ./:/app
    restart: unless-stopped